name: Publish Trackers Releases to PyPI

on:
  release:
    types: [published]
  pull_request:
    branches: ['release/*', 'develop']
    paths:
      - '.github/workflows/build-package.yml'
      - '.github/workflows/publish-release.yml'

permissions: {} # Explicitly remove all permissions by default

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build-package.yml

  publish-release:
    name: Publish Release Package
    needs: build
    if: github.event_name == 'release' && github.event.release.prerelease != true
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/trackers/
    timeout-minutes: 10
    permissions:
      id-token: write # Required for PyPI publishing
      contents: read # Required for checkout
    steps:
      - name: 📥 Download distribution artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.1.8
        with:
          name: dist
          path: dist/
      - name: List distribution artifacts
        run: ls -lh dist/

      - name: 🚀 Publish to PyPi
        # We only want to publish to PyPi if the event is a release and it's not a pre-release.
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          attestations: true

  publish-github-release:
    name: Upload GitHub Release Artifacts
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create and update GitHub Releases
    steps:
      - name: 📥 Download distribution artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/
      - name: List distribution artifacts
        run: ls -lh dist/

      - name: 📦 Upload release assets
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228  # v2.2.1
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/*
          fail_on_unmatched_files: true
          generate_release_notes: true
